# App Name
spring.application.name=Portfolio

# Mail Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javadev.nikhilkute@gmail.com
spring.mail.password=nbzu zydu mrlj pscl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true